[General]
key_pmi=5947959851
key_pmi_invite_msg="Acebuche, Fernando Jose C. is inviting you to a scheduled Zoom meeting.\r\n\r\nTopic: Acebuche, Fernando Jose C.'s Personal Meeting Room\r\nJoin Zoom Meeting\r\nhttps://us04web.zoom.us/j/5947959851?pwd=OG5vdjBJMStlWFVTbE5lSis2cVlkQT09\r\n\r\nMeeting ID: 594 795 9851\r\nPasscode: 1QPTAe\r\n\r\n"
